//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database_demo
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActualTable
    {
        public int ID_Actual { get; set; }
        public bool IsActualValue { get; set; }
        public string TextActual { get; set; }
    }
}
